redis:
  key:
    prefix: edipao
    maxLength: 200
  hostName: 172.16.170.70
  password:
  defaultDbIndex: 0
  port: 6379
  timeout: 1000
  pool:
    maxIdel: 1000
    maxTotal: 2000
    minIdel: 300
    maxWaitMillis: 2000

server:
  port: 10086
spring:
  application:
    name: selenium-autologin